name: Build and publish artifacts

on:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: write # Required to create releases and modify repository contents
  deployments: write # Required for creating deployments associated with releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: 8

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      # https://github.com/marketplace/actions/create-release
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: "build/libs/output.txt"
          bodyFile: ".github/workflows/release-body.md"
